export const products = [
  {
    id: 1,
    name: "Air Phantom X",
    brand: "Nike",
    category: "sneakers",
    price: 189,
    originalPrice: 240,
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
      "https://images.unsplash.com/photo-1608231387042-66d1773d3028?w=600&q=80",
    ],
    sizes: ["38", "39", "40", "41", "42", "43", "44", "45"],
    tags: ["limited"],
    rating: 4.9,
    reviews: 128,
    desc: "Silhouette iconique revisitée avec une semelle carbone ultra-légère. Le futur du running lifestyle.",
    colorway: "Triple White",
  },
  {
    id: 2,
    name: "Forum Low Cloud",
    brand: "Adidas",
    category: "sneakers",
    price: 145,
    originalPrice: null,
    images: [
      "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&q=80",
      "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=600&q=80",
    ],
    sizes: ["38", "39", "40", "41", "42", "43"],
    tags: ["new"],
    rating: 4.7,
    reviews: 89,
    desc: "Retour en force du classique Adidas avec une tige en cuir pleine fleur et un look court vintage.",
    colorway: "Cloud White",
  },
  {
    id: 3,
    name: "Dunk Low Panda",
    brand: "Nike",
    category: "sneakers",
    price: 210,
    originalPrice: 290,
    images: [
      "https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=600&q=80",
      "https://images.unsplash.com/photo-1584735175315-9d5df23be7be?w=600&q=80",
    ],
    sizes: ["39", "40", "41", "42", "43", "44"],
    tags: ["limited"],
    rating: 5.0,
    reviews: 312,
    desc: "Le coloris le plus demandé de la décennie. Noir et blanc immuable, design indémodable.",
    colorway: "Black / White",
  },
  {
    id: 4,
    name: "Speedcat OG",
    brand: "Puma",
    category: "sneakers",
    price: 120,
    originalPrice: null,
    images: [
      "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&q=80",
      "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&q=80",
    ],
    sizes: ["38", "39", "40", "41", "42"],
    tags: ["new"],
    rating: 4.6,
    reviews: 67,
    desc: "Le retour du Speedcat sous une forme épurée et authentique. Culture automobile made in Puma.",
    colorway: "Racing Red",
  },
  {
    id: 5,
    name: "PSG Away 2024",
    brand: "Nike",
    category: "maillots",
    price: 95,
    originalPrice: 130,
    images: [
      "https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=600&q=80",
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    tags: [],
    rating: 4.5,
    reviews: 201,
    desc: "Édition extérieur du Paris Saint-Germain, technologie Dri-FIT ADV pour une performance maximale.",
    colorway: "Midnight Navy",
  },
  {
    id: 6,
    name: "Hoodie Chrome Logo",
    brand: "FreshWare",
    category: "hauts",
    price: 89,
    originalPrice: null,
    images: [
      "https://images.unsplash.com/photo-1556821840-3a63f15232d0?w=600&q=80",
      "https://images.unsplash.com/photo-1578768079052-aa76e52ff62e?w=600&q=80",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: ["new"],
    rating: 4.8,
    reviews: 156,
    desc: "Coton 400g premium double fil. Logo chromatique thermocollé. Heavy. Dense. Définitif.",
    colorway: "Washed Black",
  },
  {
    id: 7,
    name: "Cargo Tech Wide",
    brand: "FreshWare",
    category: "bas",
    price: 112,
    originalPrice: 145,
    images: [
      "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    tags: [],
    rating: 4.4,
    reviews: 88,
    desc: "Pantalon cargo wide-leg en ripstop technique. 8 poches fonctionnelles. Silhouette architecturale.",
    colorway: "Olive Drab",
  },
  {
    id: 8,
    name: "Windbreaker Neon",
    brand: "FreshWare",
    category: "hauts",
    price: 165,
    originalPrice: null,
    images: [
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80",
      "https://images.unsplash.com/photo-1544441893-675973e31985?w=600&q=80",
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    tags: ["limited"],
    rating: 4.9,
    reviews: 42,
    desc: "Coupe-vent imperméable avec insertions réfléchissantes. Visible la nuit. Invisible le jour.",
    colorway: "Volt / Obsidian",
  },
  {
    id: 9,
    name: "Cap Structured 6-Panel",
    brand: "FreshWare",
    category: "accessoires",
    price: 45,
    originalPrice: null,
    images: [
      "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&q=80",
    ],
    sizes: ["unique"],
    tags: ["new"],
    rating: 4.6,
    reviews: 203,
    desc: "Structuré, réglable, broderie 3D. Le fondamental de toute rotation streetwear.",
    colorway: "Black / Acid",
  },
  {
    id: 10,
    name: "Crossbody Sling Tech",
    brand: "FreshWare",
    category: "accessoires",
    price: 68,
    originalPrice: 85,
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80",
    ],
    sizes: ["unique"],
    tags: [],
    rating: 4.7,
    reviews: 119,
    desc: "Nylon balistique 1000D, système MOLLE, passe-câble USB. Le sac de la génération Z.",
    colorway: "Stealth Black",
  },
  {
    id: 11,
    name: "Oversized Tee Acid",
    brand: "FreshWare",
    category: "hauts",
    price: 52,
    originalPrice: null,
    images: [
      "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=600&q=80",
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    tags: ["new"],
    rating: 4.5,
    reviews: 287,
    desc: "T-shirt oversized drop shoulder. 100% coton bio lavé. Print acide sur devant. Oversized is forever.",
    colorway: "Acid Wash",
  },
  {
    id: 12,
    name: "Track Pant Velour",
    brand: "FreshWare",
    category: "bas",
    price: 98,
    originalPrice: 125,
    images: [
      "https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?w=600&q=80",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: ["limited"],
    rating: 4.8,
    reviews: 73,
    desc: "Jogging velours 2000s revival. Bande latérale contrastante. Texture premium, fit slim tapered.",
    colorway: "Deep Burgundy",
  },
  {
    id: 13,
    name: "Real Madrid Home",
    brand: "Adidas",
    category: "maillots",
    price: 110,
    originalPrice: null,
    images: [
      "https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?w=600&q=80",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tags: [],
    rating: 4.6,
    reviews: 445,
    desc: "Domicile officiel du Real Madrid CF. Technologie HEAT.RDY. La maison des champions.",
    colorway: "White / Gold",
  },
  {
    id: 14,
    name: "Tote Bag Heavy Canvas",
    brand: "FreshWare",
    category: "accessoires",
    price: 35,
    originalPrice: null,
    images: [
      "https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&q=80",
    ],
    sizes: ["unique"],
    tags: ["new"],
    rating: 4.3,
    reviews: 167,
    desc: "Canvas 14oz double couture. Capacité 22L. Sérigraphie FreshWare. Simple. Durable. Permanent.",
    colorway: "Natural / Black",
  },
  {
    id: 15,
    name: "Mesh Short Gradient",
    brand: "FreshWare",
    category: "bas",
    price: 72,
    originalPrice: 90,
    images: [
      "https://images.unsplash.com/photo-1565084888279-aca607ecce0c?w=600&q=80",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: [],
    rating: 4.4,
    reviews: 95,
    desc: "Short mesh semi-transparent avec gradient teint en pièce. Double poche cargo. Textures contrastées.",
    colorway: "Gradient Dusk",
  },
];

export const reviews = [
  {
    id: 1,
    name: "Théo M.",
    avatar: "T",
    text: "Qualité incroyable sur les Dunk. Exactement comme les originales, livrées en 8 jours. FreshWare c'est sérieux.",
    rating: 5,
    product: "Dunk Low Panda",
    date: "Mars 2026",
  },
  {
    id: 2,
    name: "Camille R.",
    avatar: "C",
    text: "Le hoodie Chrome Logo est une tuerie. Le coton est lourd comme on aime. Je prendrai la prochaine drop les yeux fermés.",
    rating: 5,
    product: "Hoodie Chrome Logo",
    date: "Fév 2026",
  },
  {
    id: 3,
    name: "Jules V.",
    avatar: "J",
    text: "Windbreaker reçu en 6 jours. Qualité premium, les détails réfléchissants sont ouf en vrai. Rapport qualité/prix imbattable.",
    rating: 5,
    product: "Windbreaker Neon",
    date: "Jan 2026",
  },
  {
    id: 4,
    name: "Sarah D.",
    avatar: "S",
    text: "Le Speedcat OG est encore mieux en vrai. Livraison rapide, packaging soigné. Merci FreshWare 🔥",
    rating: 5,
    product: "Speedcat OG",
    date: "Avr 2026",
  },
];

export const categories = [
  { id: "all", label: "Tout" },
  { id: "sneakers", label: "Sneakers" },
  { id: "hauts", label: "Hauts" },
  { id: "bas", label: "Bas" },
  { id: "maillots", label: "Maillots" },
  { id: "accessoires", label: "Accessoires" },
];
